Lidar_front_end:
   multi_lid: 1 # 1 represent two lidars
   lid_topic: "/livox/lidar_192_168_1_3"
   lid_topic2: "/livox/lidar_192_168_1_100"
   lidar_type: 2   # 1 for Livox-avia, 2 for vlp, 3 for Ouster-OS1-64
   lidar_type2: 2
   N_SCANS: 4
   using_raw_point: 1
   point_step: 1
   LiDAR2_rotate_to_LIDAR1_Extrinsic:
      [0.938514, 0.000000,  -0.345241,
       0.000000, 1.000000,  0.0000000,
       0.345241, 0.000000,  0.938514] 
   LiDAR2_offset_to_LIDAR1_Extrinsic:
      [0.016537, -0.03939, -0.23079] 
   
r3live_common:
   if_dump_log: 0                   # If recording ESIKF update log. [default = 0]
   record_offline_map: 1            # If recording offline map. [default = 1]
   pub_pt_minimum_views: 3          # Publish points which have been render up to "pub_pt_minimum_views" time. [default = 3]
   minimum_pts_size: 0.01           # The minimum distance for every two points in Global map (unit in meter). [default = 0.01] 
   image_downsample_ratio: 1        # The downsample ratio of the input image. [default = 1]
   estimate_i2c_extrinsic: 0        # If enable estimate the extrinsic between camera and IMU. [default = 1] 
   estimate_intrinsic: 0            # If enable estimate the online intrinsic calibration of the camera lens. [default = 1] 
   maximum_vio_tracked_pts: 600     # The maximum points for tracking. [default = 600]
   append_global_map_point_step: 4  # The point step of append point to global map. [default = 4]

r3live_vio:
   image_width: 848
   image_height: 480
   camera_intrinsic:
      [605.772 , 0.0,   424.736,
      0.0,    605.545,  236.741,
      0.0, 0.0, 1.0 ] 
   camera_dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. Camera-to-LiDAR1.
   camera_ext_R:
       [0.        ,  0.34524104,  0.93851412,
        -1.        , -0.        , -0.        ,
        -0.        , -0.93851412,  0.34524104] 
   camera_ext_t: [0.08528735, 0.0304036, -0.04362076] 

   multi_camera_state: 1
   camera2_intrinsic:
      [607.575 , 0.0,   432.54,
      0.0,    607.335,  243.137,
      0.0, 0.0, 1.0 ] 
   camera2_dist_coeffs: [0.0, 0.0, 0.0, 0.0, 0.0]  #k1, k2, p1, p2, k3
   # Fine extrinsic value. Camera2-to-LiDAR1.
   camera2_ext_R:
       [-0.79491981,  0.36735248,  0.48286054,
        -0.5093022 ,  0.02847882, -0.86011692,
        -0.32971664, -0.92964638,  0.1644545 ] 
   camera2_ext_t: [0.08063143, -0.15576051, -0.10504271] 

r3live_lio:        
   lio_update_point_step: 4   # Point step used for LIO update.  
   max_iteration: 2           # Maximum times of LIO esikf.
   lidar_time_delay: 0        # The time-offset between LiDAR and IMU, provided by user. 
   filter_size_corner: 0.10   
   filter_size_surf: 0.10
   filter_size_surf_z: 0.10
   filter_size_map: 0.10
